/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    disciplines: Discipline;
    artists: Artist;
    'artist-applications': ArtistApplication;
    works: Work;
    films: Film;
    'podcast-episodes': PodcastEpisode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    disciplines: DisciplinesSelect<false> | DisciplinesSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    'artist-applications': ArtistApplicationsSelect<false> | ArtistApplicationsSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    films: FilmsSelect<false> | FilmsSelect<true>;
    'podcast-episodes': PodcastEpisodesSelect<false> | PodcastEpisodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    loader: Loader;
    nav: Nav;
    hero: Hero;
    'work-section': WorkSection;
    'about-section': AboutSection;
    'directory-section': DirectorySection;
    'media-kit-section': MediaKitSection;
    'contact-section': ContactSection;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    loader: LoaderSelect<false> | LoaderSelect<true>;
    nav: NavSelect<false> | NavSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'work-section': WorkSectionSelect<false> | WorkSectionSelect<true>;
    'about-section': AboutSectionSelect<false> | AboutSectionSelect<true>;
    'directory-section': DirectorySectionSelect<false> | DirectorySectionSelect<true>;
    'media-kit-section': MediaKitSectionSelect<false> | MediaKitSectionSelect<true>;
    'contact-section': ContactSectionSelect<false> | ContactSectionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines".
 */
export interface Discipline {
  id: number;
  name: string;
  slug: string;
  group: 'Skate' | 'Surf' | 'Música' | 'Cine' | 'Foto';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  slug: string;
  disciplines: (number | Discipline)[];
  location: string;
  bio: string;
  avatar?: (number | null) | Media;
  contactHref: string;
  featured?: boolean | null;
  order?: number | null;
  status: 'pending' | 'approved' | 'archived';
  sourceApplication?: (number | null) | ArtistApplication;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-applications".
 */
export interface ArtistApplication {
  id: number;
  name: string;
  disciplines: (number | Discipline)[];
  contact: string;
  status: 'new' | 'reviewed' | 'approved' | 'rejected';
  reviewedBy?: (number | null) | User;
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  artist: number | Artist;
  disciplines?: (number | Discipline)[] | null;
  year?: string | null;
  description?: string | null;
  media?: (number | null) | Media;
  externalUrl?: string | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films".
 */
export interface Film {
  id: number;
  title: string;
  category: string;
  year: string;
  description: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  videoUrl?: string | null;
  thumbnail?: (number | null) | Media;
  credits?: (number | Artist)[] | null;
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes".
 */
export interface PodcastEpisode {
  id: number;
  title: string;
  episodeNumber?: number | null;
  guestArtists?: (number | Artist)[] | null;
  description?: string | null;
  publishDate?: string | null;
  embedUrl?: string | null;
  thumbnail?: (number | null) | Media;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'disciplines';
        value: number | Discipline;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'artist-applications';
        value: number | ArtistApplication;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'films';
        value: number | Film;
      } | null)
    | ({
        relationTo: 'podcast-episodes';
        value: number | PodcastEpisode;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines_select".
 */
export interface DisciplinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  disciplines?: T;
  location?: T;
  bio?: T;
  avatar?: T;
  contactHref?: T;
  featured?: T;
  order?: T;
  status?: T;
  sourceApplication?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-applications_select".
 */
export interface ArtistApplicationsSelect<T extends boolean = true> {
  name?: T;
  disciplines?: T;
  contact?: T;
  status?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  artist?: T;
  disciplines?: T;
  year?: T;
  description?: T;
  media?: T;
  externalUrl?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films_select".
 */
export interface FilmsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  year?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  videoUrl?: T;
  thumbnail?: T;
  credits?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes_select".
 */
export interface PodcastEpisodesSelect<T extends boolean = true> {
  title?: T;
  episodeNumber?: T;
  guestArtists?: T;
  description?: T;
  publishDate?: T;
  embedUrl?: T;
  thumbnail?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contactEmail: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loader".
 */
export interface Loader {
  id: number;
  words?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  headline?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  tagline: string;
  subtitle: string;
  comingSoon: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-section".
 */
export interface WorkSection {
  id: number;
  sectionTitle: string;
  sectionNumber: string;
  headline?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSection {
  id: number;
  sectionTitle: string;
  sectionNumber: string;
  statement?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  bio?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  principles?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-section".
 */
export interface DirectorySection {
  id: number;
  sectionTitle: string;
  sectionNumber: string;
  headline?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  intro: string;
  joinForm: {
    sectionTitle: string;
    sectionNumber: string;
    headline?:
      | {
          line: string;
          id?: string | null;
        }[]
      | null;
    intro: string;
    form: {
      nameLabel: string;
      namePlaceholder: string;
      disciplinesLabel: string;
      contactLabel: string;
      contactPlaceholder: string;
      submitLabel: string;
      sendingLabel: string;
      successMessage: string;
      errorMessage: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-kit-section".
 */
export interface MediaKitSection {
  id: number;
  sectionTitle: string;
  sectionNumber: string;
  headline?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  intro: string;
  audience: {
    label: string;
    metrics?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  formats?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  networkLabel: string;
  cta: {
    headline: string;
    description: string;
    label: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  sectionTitle: string;
  sectionNumber: string;
  headline?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  form: {
    nameLabel: string;
    namePlaceholder: string;
    emailLabel: string;
    emailPlaceholder: string;
    messageLabel: string;
    messagePlaceholder: string;
    submitLabel: string;
  };
  footer: {
    copyright: string;
    tagline: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loader_select".
 */
export interface LoaderSelect<T extends boolean = true> {
  words?:
    | T
    | {
        word?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  headline?:
    | T
    | {
        line?: T;
        id?: T;
      };
  tagline?: T;
  subtitle?: T;
  comingSoon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-section_select".
 */
export interface WorkSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionNumber?: T;
  headline?:
    | T
    | {
        line?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionNumber?: T;
  statement?:
    | T
    | {
        line?: T;
        id?: T;
      };
  bio?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  principles?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directory-section_select".
 */
export interface DirectorySectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionNumber?: T;
  headline?:
    | T
    | {
        line?: T;
        id?: T;
      };
  intro?: T;
  joinForm?:
    | T
    | {
        sectionTitle?: T;
        sectionNumber?: T;
        headline?:
          | T
          | {
              line?: T;
              id?: T;
            };
        intro?: T;
        form?:
          | T
          | {
              nameLabel?: T;
              namePlaceholder?: T;
              disciplinesLabel?: T;
              contactLabel?: T;
              contactPlaceholder?: T;
              submitLabel?: T;
              sendingLabel?: T;
              successMessage?: T;
              errorMessage?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-kit-section_select".
 */
export interface MediaKitSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionNumber?: T;
  headline?:
    | T
    | {
        line?: T;
        id?: T;
      };
  intro?: T;
  audience?:
    | T
    | {
        label?: T;
        metrics?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  formats?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  networkLabel?: T;
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section_select".
 */
export interface ContactSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionNumber?: T;
  headline?:
    | T
    | {
        line?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  form?:
    | T
    | {
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
      };
  footer?:
    | T
    | {
        copyright?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}